type <%- modelName %> {
  _id: ID!
<%- schemaBody %>
  createdAt: Date
  updatedAt: Date
}

input <%- modelName %>Input {
<%- schemaInputBody %>
}

type Query {
  <%- varName %>(_id: ID!): <%- modelName %>
  <%- pluralVarName %>: [<%- modelName %>]
}

type Mutation {
  create<%- modelName %>(input: <%- modelName %>Input): <%- modelName %>
  update<%- modelName %>(_id: ID!, input: <%- modelName %>Input): <%- modelName %>
  delete<%- modelName %>(_id: ID!): <%- modelName %>
}
