type Article {
  _id: ID!
  title: String
  content: String
  keyName: String
  createdAt: Date
  updatedAt: Date
}

input ArticleInput {
  title: String
  content: String
  keyName: String
}

type Query {
  article(_id: ID!): Article
  articles: [Article]
}

type Mutation {
  createArticle(input: ArticleInput): Article
  updateArticle(_id: ID!, input: ArticleInput): Article
  deleteArticle(_id: ID!): Article
}
