type User {
  _id: ID!
  good: Boolean
  createdAt: Date
  updatedAt: Date
}

input UserInput {
  good: Boolean
}

type Query {
  user(_id: ID!): User
  users: [User]
}

type Mutation {
  createUser(input: UserInput): User
  updateUser(_id: ID!, input: UserInput): User
  deleteUser(_id: ID!): User
}
