type UserRole {
  name: String
  permissions: [String]
}

type User {
  _id: ID!
  age: String
  roles: [UserRole]
  name: String
  createdAt: Date
  updatedAt: Date
}

input UserInput {
  age: String
  roles: [UserRole]
  name: String
}

type Query {
  user(_id: ID!): User
  users: [User]
}

type Mutation {
  createUser(input: UserInput): User
  updateUser(_id: ID!, input: UserInput): User
  deleteUser(_id: ID!): User
}
