type UserSettingsPush {
  first: Boolean
  second: Boolean
}

input UserSettingsPushInput {
  first: Boolean
  second: Boolean
}

type UserSettings {
  sms: Boolean
  email: Boolean
  push: UserSettingsPush
}

input UserSettingsInput {
  sms: Boolean
  email: Boolean
  push: UserSettingsPushInput
}

type UserAddressAddress {
  one: String
  two: String
}

input UserAddressAddressInput {
  one: String
  two: String
}

type UserAddress {
  city: String
  province: String
  region: String
  address: UserAddressAddress
}

input UserAddressInput {
  city: String
  province: String
  region: String
  address: UserAddressAddressInput
}

type User {
  _id: ID!
  name: String
  settings: UserSettings
  age: Int
  address: UserAddress
  createdAt: Date
  updatedAt: Date
}

input UserInput {
  name: String
  settings: UserSettingsInput
  age: Int
  address: UserAddressInput
}

type Query {
  user(_id: ID!): User
  users: [User]
}

type Mutation {
  createUser(input: UserInput): User
  updateUser(_id: ID!, input: UserInput): User
  deleteUser(_id: ID!): User
}
