type User {
  _id: ID!
  address: Address
  addresses: [Address]
  createdAt: Date
  updatedAt: Date
}

input UserInput {
  address: AddressInput
  addresses: [AddressInput]
}

type Query {
  user(_id: ID!): User
  users: [User]
}

type Mutation {
  createUser(input: UserInput): User
  updateUser(_id: ID!, input: UserInput): User
  deleteUser(_id: ID!): User
}
