type UserInfo {
  photo: File
}

input UserInfoInput {
  photo: Upload
}

type User {
  _id: ID!
  info: UserInfo
  createdAt: Date
  updatedAt: Date
}

input UserInput {
  info: UserInfoInput
}

type Query {
  user(_id: ID!): User
  users: [User]
}

type Mutation {
  createUser(input: UserInput): User
  updateUser(_id: ID!, input: UserInput): User
  deleteUser(_id: ID!): User
}
