module.exports = (type, _modifiers, _param) => {
  switch (type) {
    case 'STRING':
      return 'String';
    case 'STRING.BINARY':
      return 'String';
    case 'CHAR':
      return 'String';
    case 'TEXT':
      return 'String';
    case 'TINYINT':
      return 'Int';
    case 'SMALLINT':
      return 'Int';
    case 'MEDIUMINT':
      return 'Int';
    case 'INTEGER':
      return 'Int';
    case 'BIGINT':
      return 'Int';
    case 'FLOAT':
      return 'Float';
    case 'DOUBLE':
      return 'Float';
    case 'DECIMAL':
      return 'Float';
    case 'REAL':
      return 'Float';
    case 'BOOLEAN':
      return 'Boolean';
    case 'ENUM':
      return 'Enum';
    case 'DATE':
      return 'Date';
    case 'DATEONLY':
      return 'Date';
    case 'TIME':
      return 'Date';
    case 'UUID':
      return 'String';
    case 'UUIDV1':
      return 'String';
    case 'UUIDV4':
      return 'String';
    case 'JSON':
      return 'Mixed';
    case 'JSONB':
      return 'Mixed';
  }
};
